- name: Install Golang
  become: true
  shell: |
    wget https://go.dev/dl/go1.22.4.linux-amd64.tar.gz
    tar -C /usr/local -xzf go1.22.4.linux-amd64.tar.gz
    rm go1.22.4.linux-amd64.tar.gz
  args:
    creates: /usr/local/go/bin/go
