- name: Install Zsh
  become: true
  apt:
    name: zsh
    state: present

- name: Change default shell to zsh
  become: true
  shell: chsh -s /usr/bin/zsh anant

- name: Install Oh My Zsh
  shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" || true
  args:
    creates: /home/anant/.oh-my-zsh
  environment:
    ZSH: /home/anant/.oh-my-zsh

- name: Update .zshrc to include Go path
  become: true
  become_user: anant
  lineinfile:
    path: /home/anant/.zshrc
    line: "export PATH=$PATH:/usr/local/go/bin"
    insertafter: "plugins="
